### ISSUE TITLE
AttributeError while running the activity

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/XOlympics#6]
This activity seems to have a few errors as of now. 
```$sugar-activity .``` throws following error:
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 159, in main
    splitted_module = activity_class.rsplit('.', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by quozl** [comment]
Possibly caused by activity.info not yet ported to latest Sugar.
